markdown: kramdown
permalink: /:year/:month/:day/:title/
url: artist.cf
author: admin
highlighter: rouge
exclude: ["Rakefile", "CNAME", "README.md"]
safe: false
paginate: 15


# Gems
gems: [jekyll-paginate]
